#pragma once

#include <GLEW/include/glew.h>

const int SKYBOX_TEXTURE_UNIT = GL_TEXTURE0;
const int SHADER_SKYBOX_TEXTURE_UNIT = 0;

const int BEACH_SAND_TEXTURE_UNIT = GL_TEXTURE1;
const int SHADER_BEACH_SAND_TEXTURE_UNIT = 1;

const int PLAINS_GRASS_TEXTURE_UNIT = GL_TEXTURE2;
const int SHADER_PLAINS_GRASS_TEXTURE_UNIT = 2;

const int PLAINS_ROCK_TEXTURE_UNIT = GL_TEXTURE3;
const int SHADER_PLAINS_ROCK_TEXTURE_UNIT = 3;

const int PLAINS_SNOW_TEXTURE_UNIT = GL_TEXTURE4;
const int SHADER_PLAINS_SNOW_TEXTURE_UNIT = 4;

const int DESERT_SAND_TEXTURE_UNIT = GL_TEXTURE5;
const int SHADER_DESERT_SAND_TEXTURE_UNIT = 5;

const int DESERT_ROCK_TEXTURE_UNIT = GL_TEXTURE6;
const int SHADER_DESERT_ROCK_TEXTURE_UNIT = 6;

const int WATER_TEXTURE_UNIT = GL_TEXTURE7;
const int SHADER_WATER_TEXTURE_UNIT = 7;